import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Navigations from '@/components/navigation';
import ClockProvider from '@/app/clock-provider';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '800'],
  style: 'normal',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ClockProvider>
          <main className="w-full max-w-[480px] mx-auto overflow-x-hidden">
            <Navigations />
            {children}
          </main>
        </ClockProvider>
      </body>
    </html>
  )
}
